### ISSUE TITLE
notebooks/jupyter/jupyter_notebook_example.ipynb: running skil_client.Credentials gives AttributeError

### ISSUE THREAD

**Issue by codevoider** [SkymindIO/SKIL_Examples#24]
I was able to run through the example notebook until **Add the Model History Server ID here** section.  Please find the error from running `skil_client.Credentials` below.

> Authenticating with SKIL API...
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-15-8877b3109def> in <module>
>      22 try:
>      23     print("Authenticating with SKIL API...")
> ---> 24     credentials = skil_client.Credentials(user_id="admin", password="admin") # Update this with the ID and password you're using for your SKIL server
>      25     token = api_instance.login(credentials)
>      26     pp.pprint(token)
> 
> AttributeError: module 'skil_client' has no attribute 'Credentials'

**Comment by ShamsUlAzeem** [comment]
@codevoider thank you for reporting this. The `Credentials` object was updated to `LoginRequest`. I've updated the example. Can you confirm if it's working now?

**Comment by codevoider** [comment]
@ShamsUlAzeem Works fine now. thank you!
